const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const icons={
 menu:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 6h16M4 12h16M4 18h16"/></svg>',
 home:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z"/><path d="M9 21v-7h6v7"/></svg>',
 book:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 5a2 2 0 0 1 2-2h13v17H6a2 2 0 0 0-2 2z"/><path d="M6 20h13"/></svg>',
 quiz:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="9"/><path d="M9.5 9a2.5 2.5 0 1 1 4.2 1.8c-.9.7-1.7 1.1-1.7 2.4M12 17h.01"/></svg>',
 jp:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 4h14v16H5z"/><path d="M8 8h8M8 12h8M8 16h5"/></svg>',
 image:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8" cy="9" r="1.5"/><path d="m4 18 5-5 3 3 2-2 6 5"/></svg>',
 search:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>',
 chart:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 19V5M4 19h16"/><path d="M8 16v-5M12 16V7M16 16v-9M20 16v-4"/></svg>',
 sun:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41"/></svg>',
 moon:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 12.8A8.5 8.5 0 1 1 11.2 3 6.5 6.5 0 0 0 21 12.8z"/></svg>',
 stop:'<svg viewBox="0 0 24 24" fill="currentColor"><rect x="6" y="6" width="12" height="12" rx="2"/></svg>',
 play:'<svg viewBox="0 0 24 24" fill="currentColor"><path d="M8 5v14l11-7z"/></svg>'
};
$('#menuBtn').innerHTML=icons.menu;$('#stopVoice').innerHTML=icons.stop;
$$('.nav').forEach(n=>{const i=n.dataset.icon;if(i&&icons[i])n.insertAdjacentHTML('afterbegin',`<span class="nav-icon">${icons[i]}</span>`);});
let pages=[],studyPages=[],curriculum={},mcqs=[],jpData={},imageMap={},visualGroups={},jpCare={};
const state={view:'dashboard',lesson:null,search:'',visualSearch:'',jpSet:'all',quizIndex:0,answered:false,quizOrder:[],theme:localStorage.getItem('ssw-theme')||'light'};
const progressKey='ssw-progress-v2';
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function getProgress(){try{return JSON.parse(localStorage.getItem(progressKey)||'{}')}catch{return {}}}
function saveProgress(p){localStorage.setItem(progressKey,JSON.stringify(p))}
function allLessons(){return (curriculum.parts||[]).flatMap(p=>p.lessons||[])}
function lessonForPage(n){return allLessons().find(l=>n>=l.pages[0]&&n<=l.pages[1])}
function studyForPage(n){return studyPages.find(p=>p.page===n)}
function pageImages(n){return (imageMap.references||[]).filter(r=>+r.page===+n&&!r.duplicate).map(r=>r.image)}
function applyTheme(){document.documentElement.dataset.theme=state.theme;$('#themeBtn').innerHTML=state.theme==='dark'?icons.sun:icons.moon;localStorage.setItem('ssw-theme',state.theme)}
applyTheme();
function shell(title,desc,badge=''){return `<div class="main"><div class="page-head"><div><div class="eyebrow">SSW CAREGIVER MASTER</div><h1>${esc(title)}</h1><p>${esc(desc)}</p></div>${badge?`<span class="soft-badge">${esc(badge)}</span>`:''}</div>`}
function render(){ $$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===state.view)); if(state.view==='dashboard')dashboard();else if(state.view==='study')study();else if(state.view==='mcq')mcq();else if(state.view==='japanese')japanese();else if(state.view==='visuals')visuals();else if(state.view==='search')search();else progress(); }
function dashboard(){
 const p=getProgress(), done=Object.keys(p.read||{}).length, acc=p.attempts?Math.round((p.correct||0)/p.attempts*100):0;
 const lessons=allLessons(); const last=localStorage.getItem('ssw-last-lesson')||'l1'; const lastL=lessons.find(x=>x.id===last)||lessons[0];
 const pct=Math.min(100,Math.round(done/112*100));
 const quick=[
  {view:'study',icon:icons.book,title:'Study Lessons',desc:'Complete Parts 1–4 with illustrations'},
  {view:'mcq',icon:icons.quiz,title:'MCQ Practice',desc:`${mcqs.length} exam-focused practice questions`},
  {view:'japanese',icon:icons.jp,title:'Japanese Care Language',desc:'Official source pages + 52 questions'},
  {view:'visuals',icon:icons.image,title:'Visual Library',desc:'314 preserved source illustrations'},
  {view:'search',icon:icons.search,title:'Search',desc:'Find English, Sinhala or Japanese terms'},
  {view:'progress',icon:icons.chart,title:'My Progress',desc:`${acc}% current MCQ accuracy`}
 ];
 const topicImages=(imageMap.references||[]).filter(r=>!r.duplicate).slice(0,6).map(r=>r.image);
 app.innerHTML=`${shell('Dashboard','Your premium SSW Caregiver study space — calm, visual and built for focused mobile study.','Offline ready')}
 <section class="premium-hero"><div class="hero-copy"><div class="hero-brand-row"><img src="icon-caregiver.svg" alt="Careworker" class="hero-care-icon"><div><span class="eyebrow light">SSW CAREGIVER MASTER</span><div class="hero-mini-title">English · සිංහල · 日本語</div></div></div><h2>Learn · Listen · Practise · Master</h2><p>One focused study space for the Care Worker exam — with preserved source content, Japanese technical terminology, Sinhala explanations and visual learning.</p><div class="hero-actions"><button class="btn light" data-lesson="${lastL.id}">Continue ${esc(lastL.title)}</button><button class="btn glass" data-go="mcq">Start MCQ</button></div></div><div class="hero-progress"><div class="progress-ring" style="--p:${pct}%"><span>${pct}%</span></div><b>${done} / 112</b><small>pages studied</small></div></section>
 <section class="progress-strip"><div><span>Lessons</span><b>${lessons.length}</b></div><div><span>MCQ Practice</span><b>${mcqs.length}</b></div><div><span>Japanese Questions</span><b>52</b></div><div><span>Illustrations</span><b>314</b></div></section>
 <section class="section"><div class="section-title"><h2>Quick Start</h2><span class="part-meta">Choose where you want to study</span></div><div class="premium-quick-grid">${quick.map(q=>`<button class="premium-quick-card" data-go="${q.view}"><div class="premium-qicon">${q.icon}</div><b>${q.title}</b><small>${q.desc}</small><span class="arrow">→</span></button>`).join('')}</div></section>
 <section class="section"><div class="section-title"><h2>Quick Start Topics</h2><span class="part-meta">Real source illustrations from your study data</span></div><div class="topic-preview-grid">${['Mobility Care','Meal Assistance','Elimination','Grooming','Bathing & Hygiene','Housework'].map((t,i)=>`<button class="topic-preview" data-go="study"><img src="assets/images/${esc(topicImages[i%topicImages.length]||'img-001.png')}" alt="${esc(t)} source illustration"><div><b>${t}</b><small>Open study</small></div></button>`).join('')}</div></section>
 <section class="section"><div class="section-title"><h2>Complete Curriculum</h2><span class="part-meta">4 Parts · ${lessons.length} chapters</span></div>${(curriculum.parts||[]).map((part,pi)=>`<article class="part-card"><div class="part-head"><div><div class="part-title">${esc(part.title)}</div><div class="part-meta">${part.lessons.length} chapters</div></div><span class="soft-badge">PART ${pi+1}</span></div><div class="lesson-grid">${part.lessons.map((l,i)=>lessonCard(l,(pi*3+i)%4)).join('')}</div></article>`).join('')}</section>`;
}
function lessonCard(l,idx){const p=getProgress(), total=Math.max(1,l.pages[1]-l.pages[0]+1), done=[...Array(total)].filter((_,i)=>p.read?.[l.pages[0]+i]).length;return `<button class="lesson-card" style="--accent:${['#2d7ff0','#22a896','#7b61d8','#f2a33b'][idx]}" data-lesson="${l.id}"><span class="lesson-no">${esc(l.id.toUpperCase())} · ${l.pages[0]}–${l.pages[1]}</span><b>${esc(l.title)}</b><small>${done}/${total} pages studied</small><div class="lesson-progress"><i style="width:${Math.round(done/total*100)}%"></i></div></button>`}
function lessonImageGroup(page){return visualGroups[String(page)]||{images:[],sourcePages:[],mergedFrom:[]}}
function imageRefsForPage(page){return (imageMap.references||[]).filter(r=>+r.page===+page&&!r.duplicate).map(r=>r.image)}
function isIllustrationOnlyPage(p){
 const raw=String(p?.text||'').replace(/\r/g,'').split(/\n+/).map(x=>x.trim()).filter(Boolean);
 if(!raw.length)return true;
 const cleaned=raw.filter(x=>{
   if(/^Original source illustrations/i.test(x))return false;
   if(/^Source PDF p\./i.test(x))return false;
   if(/^Images are extracted from the original uploaded/i.test(x))return false;
   if(/^PART\s+\d+/i.test(x))return false;
   if(/^Understanding of People in Need of Nursing Care$/i.test(x))return false;
   if(/^Basics of Communication$/i.test(x))return false;
   if(/^Communication with Users$/i.test(x))return false;
   if(/^Communication with Team Members$/i.test(x))return false;
   if(/^Walking \/ Lifting \/ Transferring$/i.test(x))return false;
   if(/^Nursing Care at Mealtimes$/i.test(x))return false;
   if(/^Nursing Care Related to Elimination Needs$/i.test(x))return false;
   if(/^Nursing Care Related to Grooming$/i.test(x))return false;
   if(/^Nursing Care Related to Bathing \/ Keeping Clean$/i.test(x))return false;
   if(/^Nursing Care Related to Housework$/i.test(x))return false;
   return true;
 });
 return cleaned.length===0;
}
function mergedImageGroupForPage(page,source,lesson){
 const base=lessonImageGroup(page);
 const imgs=[...(base.images||[])], pages=[...(base.sourcePages||[])], merged=[...(base.mergedFrom||[])];
 const add=(im,pg)=>{if(im&&!imgs.includes(im))imgs.push(im);if(pg&&!pages.includes(pg))pages.push(pg)};
 (imageRefsForPage(page)).forEach(im=>add(im,page));
 // Attach illustration-only source pages to the next substantive content page in the same chapter.
 const idx=source.findIndex(x=>x.page===page);
 if(idx>=0){
   for(let j=idx-1;j>=0;j--){
     const prev=source[j];
     if(!isIllustrationOnlyPage(prev))break;
     imageRefsForPage(prev.page).forEach(im=>add(im,prev.page));
     if(!merged.includes(prev.page))merged.push(prev.page);
   }
 }
 return {images:imgs,sourcePages:pages.sort((a,b)=>a-b),mergedFrom:merged.sort((a,b)=>a-b)};
}
function stripBoilerplate(text){return String(text||'').replace(/Original source illustrations[\s\S]*?no image content was invented or replaced\.?/gi,'').trim()}
function voiceButton(text,lang,label){const t=String(text||'').trim();if(!t)return '';return `<button class="voice voice-small ${lang.startsWith('ja')?'ja':''} ${lang.startsWith('si')?'si':''}" data-speak="${esc(t)}" data-lang="${lang}" aria-label="Read ${esc(label)}">🔊 <span>${esc(label)}</span></button>`}
function parseTriLine(line){const x=line.trim().replace(/^[🇯🇵🇬🇧🇱🇰]\s*/,'');const m=x.match(/^(.+?)\s+—\s+(.+?)\s+—\s+(.+)$/);return m?{jp:m[1].trim(),en:m[2].trim(),si:m[3].trim()}:null}
function parseFlagGroup(lines,i){if(!/^🇯🇵\s*/.test(lines[i]))return null;const jp=lines[i].replace(/^🇯🇵\s*/,'').trim(),en=(lines[i+1]||'').replace(/^🇬🇧\s*/,'').trim(),si=(lines[i+2]||'').replace(/^🇱🇰\s*/,'').trim();if(!lines[i+1]?.startsWith('🇬🇧')||!lines[i+2]?.startsWith('🇱🇰'))return null;return{jp,en,si,next:i+3}}
function isHeading(line){const x=line.trim();return /^(?:PART\s+\d+|(?:\d+|\d+\.\d+)\.\s+[A-Z][A-Z0-9 /()'’—–-]{3,}|[A-Z][A-Z0-9 /()'’—–-]{7,})$/.test(x)||/^(?:HUMAN DIGNITY|QUALITY OF LIFE|NORMALIZATION|SELF-|INDEPENDENCE|USER-CENTERED|ROLE|PROFESSIONAL|SAFETY|RISK|UNDERSTANDING|COMMUNICATION|WALKING|NURSING CARE|ELIMINATION|GROOMING|BATHING|HOUSEWORK|MEALS|SWALLOWING|POSITIONS|COMFORTABLE POSITIONS|DISUSE SYNDROME|PRESSURE ULCER|ASSISTIVE DEVICES|BASIC TRANSFER|STANDING|STAIRS|SENUKI|CARE PROCESS|HANDWASHING|DRESSING|FEMALE|WHEELCHAIR|FINAL SOURCE|HIGH-YIELD)/i.test(x)}
function renderContentBlocks(lines){let html='',i=0;while(i<lines.length){const line=lines[i];if(line.startsWith('•')){const items=[];while(i<lines.length&&lines[i].startsWith('•')){items.push(lines[i].slice(1).trim());i++}html+=`<div class="study-block bullet-block"><ul>${items.map(x=>`<li><span>${esc(x)}</span>${voiceButton(x,'en-US','English')}</li>`).join('')}</ul></div>`;continue}if(/^\d+[.)]\s+/.test(line)){const items=[];while(i<lines.length&&/^\d+[.)]\s+/.test(lines[i])){items.push(lines[i].replace(/^\d+[.)]\s+/,'').trim());i++}html+=`<div class="study-block ordered-block"><ol>${items.map(x=>`<li><span>${esc(x)}</span>${voiceButton(x,'en-US','English')}</li>`).join('')}</ol></div>`;continue}const buf=[line];i++;while(i<lines.length&&!lines[i].startsWith('•')&&!/^\d+[.)]\s+/.test(lines[i])&&!isHeading(lines[i])&&!parseTriLine(lines[i])&&!parseFlagGroup(lines,i)){buf.push(lines[i]);i++}const text=buf.join(' ');html+=`<div class="study-block paragraph-block"><p>${esc(text)}</p><div class="block-voices">${voiceButton(text,'en-US','English')}</div></div>`}return html}
function formatStudyText(t){if(!t)return '<div class="source-page-note">This source page is visual/reference material. Its original illustrations are shown in the visual panel.</div>';const lines=stripBoilerplate(t).split(/\n+/).map(x=>x.trim()).filter(Boolean);let html='',i=0;while(i<lines.length){const fg=parseFlagGroup(lines,i);if(fg){html+=`<section class="study-block trilingual-block"><div class="term-grid"><div><span class="lang-label">🇯🇵 Japanese</span><strong>${esc(fg.jp)}</strong></div><div><span class="lang-label">🇬🇧 English</span><strong>${esc(fg.en)}</strong></div><div><span class="lang-label">🇱🇰 Sinhala</span><strong>${esc(fg.si)}</strong></div></div><div class="block-voices">${voiceButton(fg.jp,'ja-JP','日本語')}${voiceButton(fg.en,'en-US','English')}${voiceButton(fg.si,'si-LK','සිංහල')}</div></section>`;i=fg.next;continue}const tri=parseTriLine(lines[i]);if(tri){html+=`<section class="study-block term-line"><div class="term-grid"><div><span class="lang-label">🇯🇵 Japanese</span><strong>${esc(tri.jp)}</strong></div><div><span class="lang-label">🇬🇧 English</span><strong>${esc(tri.en)}</strong></div><div><span class="lang-label">🇱🇰 Sinhala</span><strong>${esc(tri.si)}</strong></div></div><div class="block-voices">${voiceButton(tri.jp,'ja-JP','日本語')}${voiceButton(tri.en,'en-US','English')}${voiceButton(tri.si,'si-LK','සිංහල')}</div></section>`;i++;continue}if(isHeading(lines[i])){const h=lines[i++];let buf=[];while(i<lines.length&&!isHeading(lines[i])&&!parseTriLine(lines[i])&&!parseFlagGroup(lines,i)){buf.push(lines[i]);i++}html+=`<section class="topic-section"><h3>${esc(h)}</h3>${renderContentBlocks(buf)}</section>`;continue}let buf=[];while(i<lines.length&&!isHeading(lines[i])&&!parseTriLine(lines[i])&&!parseFlagGroup(lines,i)){buf.push(lines[i]);i++}html+=renderContentBlocks(buf)}return html}
function study(){if(!state.lesson){app.innerHTML=`${shell('Study','The complete master curriculum is organized by Parts 1–4. Source illustrations are grouped with the nearest substantive study content so chapters remain readable.','14 chapters')}<section class="premium-study-intro"><div><span class="eyebrow">CAREWORKER STUDY MODE</span><h2>Study by topic — not by scattered source pages.</h2><p>Each topic has clear spacing, trilingual terminology, focused audio controls and preserved source illustrations.</p></div><div class="intro-pill">🇯🇵 · 🇬🇧 · 🇱🇰</div></section>${(curriculum.parts||[]).map((part,pi)=>`<section class="part-card"><div class="part-head"><div><div class="part-title">${esc(part.title)}</div><div class="part-meta">Complete chapter list from the master study structure</div></div><span class="soft-badge">${part.lessons.length} chapters</span></div><div class="lesson-grid">${part.lessons.map((l,i)=>lessonCard(l,(pi*3+i)%4)).join('')}</div></section>`).join('')}</div>`;return}const l=allLessons().find(x=>x.id===state.lesson);if(!l)return;localStorage.setItem('ssw-last-lesson',l.id);const source=pages.filter(p=>p.page>=l.pages[0]&&p.page<=l.pages[1]);const substantive=source.filter(p=>!isIllustrationOnlyPage(p));app.innerHTML=`${shell(l.title,`${l.pages[0]}–${l.pages[1]} master pages • source illustrations grouped with study topics`,'Complete chapter')}<div class="study-toolbar"><button class="btn secondary" data-back>← All chapters</button><button class="btn secondary" data-study-top>↑ Top</button><span class="soft-badge">${substantive.length} content sections</span></div><section class="lesson-overview"><div class="eyebrow">${esc(l.id.toUpperCase())}</div><h2>${esc(l.title)}</h2><p>Topics and sub-topics are separated for easier reading. Original illustrations from source-only pages are preserved beside the relevant chapter content.</p></section><div class="chapter-flow">${substantive.map(p=>renderSourcePage(p,source,l)).join('')}</div></div>`}
function renderSourcePage(p,source,lesson){const sp=studyForPage(p.page),display=sp?.text||p.text||'',clean=stripBoilerplate(display),group=mergedImageGroupForPage(p.page,source,lesson),imgs=group.images||[],visible=imgs.slice(0,8);return `<article class="study-card rich-study-card page-section" id="page-${p.page}"><div class="page-meta"><span class="page-no">MASTER PAGE ${p.page}</span><button class="mark ${getProgress().read?.[p.page]?'done':''}" data-mark="${p.page}">${getProgress().read?.[p.page]?'✓ Studied':'Mark studied'}</button></div>${p.topics?.length?`<div class="topic-row">${p.topics.slice(0,8).map(t=>`<span class="topic">${esc(t)}</span>`).join('')}</div>`:''}<div class="study-layout"><div class="note-content">${formatStudyText(clean)}</div>${imgs.length?`<aside class="image-rail"><div class="image-rail-title"><span>🖼️ Source illustrations</span><span class="image-count">${imgs.length}</span></div><div class="image-stack">${visible.map(im=>`<button class="source-thumb" data-image="${esc(im)}"><img loading="lazy" src="assets/images/${esc(im)}" alt="Original source illustration"><span>View</span></button>`).join('')}</div><div class="image-rail-meta">${imgs.length} preserved illustration${imgs.length===1?'':'s'}${group.sourcePages?.length?`<br>Source PDF pages: ${group.sourcePages.join(', ')}`:''}</div></aside>`:''}</div></article>`}
function mcq(){if(!state.quizOrder.length)state.quizOrder=mcqs.map((_,i)=>i);const q=mcqs[state.quizOrder[state.quizIndex%state.quizOrder.length]];const p=getProgress();const acc=p.attempts?Math.round((p.correct||0)/p.attempts*100):0;app.innerHTML=`${shell('MCQ Exam Practice','Exam-focused questions with Japanese technical terminology and Sinhala explanations.','50+ practice')}
 <div class="quiz-layout"><section class="quiz-card"><div class="quiz-top"><span>QUESTION ${state.quizIndex%state.quizOrder.length+1} / ${state.quizOrder.length}</span><span>${esc(q.id||'')}</span></div><h2>${esc(q.question||q.q||'')}</h2>${q.jp||q.term?`<div class="term"><div><small>日本語</small><strong>${esc(q.jp||q.term)}</strong></div><button data-speak="${esc(q.jp||q.term)}" data-lang="ja-JP">🔊</button></div>`:''}<div class="si-explain">${esc(q.sinhala||q.explanation_si||'ප්‍රශ්නයට අදාළ ප්‍රධාන කරුණ නැවත අධ්‍යයනය කරන්න.')}</div><div class="options">${(q.options||[]).map((o,i)=>`<button class="option" data-opt="${i}"><b>${String.fromCharCode(65+i)}</b><span>${esc(o)}</span></button>`).join('')}</div><div id="feedback"></div></section><aside class="quiz-side"><div class="side-stat"><b>${p.correct||0}</b><small>Correct</small></div><div class="side-stat"><b>${p.attempts||0}</b><small>Attempts</small></div><div class="side-stat"><b>${acc}%</b><small>Accuracy</small></div><button class="btn" style="width:100%;margin-top:12px" data-next>Next question →</button><button class="btn secondary" style="width:100%;margin-top:7px" data-reset-quiz>Restart</button></aside></div></div>`}
function japanese(){const sets=jpData.sets||[],qs=jpData.questions||[],selected=state.jpSet==='all'?null:state.jpSet,show=qs.filter(q=>!selected||q.set===selected),carePages=jpCare?.pages||[];app.innerHTML=`${shell('Japanese Care Language','Complete official Nursing Care Japanese Language source section plus the 52 official question records.','68 source pages · 52 questions')}<div class="jp-summary"><div class="summary-card"><b>68</b><small>official care-language source pages</small></div><div class="summary-card"><b>52</b><small>official answer-key questions</small></div><div class="summary-card"><b>${sets.length}</b><small>question sets</small></div></div><section class="section jp-care-section"><div class="section-title"><h2>🇯🇵 Complete Japanese Care Language</h2><span class="part-meta">Official source pages 205–272</span></div><div class="jp-source-pages">${carePages.map(renderJapaneseSourcePage).join('')}</div></section><section class="section"><div class="section-title"><h2>Official 52-question practice</h2><span class="part-meta">Answer key preserved separately</span></div><div class="jp-filter"><button class="btn ${selected?'secondary':''}" data-jpset="all">All sets</button>${sets.map(s=>`<button class="btn ${selected===s.title?'':'secondary'}" data-jpset="${esc(s.title)}">${esc(s.title)}</button>`).join('')}</div><div class="jp-grid">${sets.filter(s=>!selected||s.title===selected).map(s=>`<article class="jp-card"><div class="eyebrow">OFFICIAL SET</div><h2>${esc(s.title)}</h2><p>Source pages: ${s.pages.join(', ')}</p><div class="answer-row">${s.answers.map((a,i)=>`<span>${i+1}: <b>${a}</b></span>`).join('')}</div><div class="voice-row">${voiceButton(s.title,'ja-JP','日本語')}</div></article>`).join('')}</div><div class="jp-grid">${show.map(q=>`<article class="jp-card jp-question"><div class="eyebrow">QUESTION ${q.number}</div><h3>${esc(q.set)}</h3><img loading="lazy" src="assets/jp-pages/${esc(q.image)}" alt="Official Japanese question page ${q.sourcePage}"><p><b>Official answer:</b> ${q.answer} · Source page ${q.sourcePage}</p><div class="voice-row">${voiceButton(q.set,'ja-JP','日本語')}</div></article>`).join('')}</div></section></div>`}
function renderJapaneseSourcePage(p){const lines=String(p.text||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);const body=lines.map(line=>{const hasJ=/[\u3040-\u30ff\u3400-\u9fff]/.test(line),hasEn=/[A-Za-z]/.test(line);const lang=hasJ&&!hasEn?'ja-JP':hasEn&&!hasJ?'en-US':null;return `<div class="jp-source-line"><span>${esc(line)}</span>${lang?voiceButton(line,lang,lang==='ja-JP'?'日本語':'English'):''}</div>`}).join('');return `<article class="jp-source-card"><div class="page-meta"><span class="page-no">OFFICIAL SOURCE PAGE ${p.sourcePage}</span><span class="soft-badge">Nursing Care Japanese Language</span></div><div class="jp-source-body">${body}</div></article>`}
function visuals(){const unique=[...new Set((imageMap.references||[]).filter(r=>!r.duplicate).map(r=>r.image))];const q=(state.visualSearch||'').toLowerCase();const list=unique.filter(im=>`${im} ${(imageMap.references||[]).filter(r=>r.image===im).map(r=>r.page).join(' ')}`.toLowerCase().includes(q));app.innerHTML=`${shell('Visual Library','314 original illustrations extracted from the master PDF and stored locally.','314 images')}
 <div class="visual-tools"><input id="visualSearch" class="searchbox" placeholder="Search filename or source page..." value="${esc(state.visualSearch)}"><span class="soft-badge">${list.length}/${unique.length}</span></div><div class="visual-grid">${list.map((im,i)=>{const ref=(imageMap.references||[]).find(r=>r.image===im);return `<button class="visual-card" data-image="${esc(im)}"><img loading="lazy" src="assets/images/${esc(im)}" alt="Original PDF illustration"><b>Illustration ${i+1}</b><small>Source PDF page ${ref?.page||'—'}</small></button>`}).join('')}</div></div>`}
function search(){const q=(state.search||'').trim().toLowerCase();const hits=q?pages.filter(p=>(p.text||'').toLowerCase().includes(q)).slice(0,100):[];app.innerHTML=`${shell('Search','Search every bundled master page across English, Sinhala and Japanese.','112 pages')}
 <input id="searchInput" class="searchbox" value="${esc(state.search)}" placeholder="Try: QOL, dementia, swallowing, urine, 生活, මුත්රා..."><p class="part-meta">${q?hits.length+' matching pages':'Search by concept, technical term or Japanese/Sinhala word.'}</p><div class="search-results">${hits.map(h=>`<button class="result" data-open-study="${h.page}"><b>Master page ${h.page}</b><span>${esc((h.text||'').slice(0,500))}</span></button>`).join('')}</div></div>`}
function progress(){const p=getProgress(),done=Object.keys(p.read||{}).length,acc=p.attempts?Math.round((p.correct||0)/p.attempts*100):0, pct=Math.min(100,Math.round(done/112*100));app.innerHTML=`${shell('Progress','Your study history stays on this device.','Local progress')}
 <div class="progress-grid"><div class="card"><b>${done}</b><small>pages studied</small></div><div class="card"><b>${p.correct||0}</b><small>correct MCQs</small></div><div class="card"><b>${p.attempts||0}</b><small>attempts</small></div><div class="card"><b>${acc}%</b><small>MCQ accuracy</small></div></div><section class="section"><div class="card" style="padding:20px;display:flex;gap:25px;align-items:center;flex-wrap:wrap"><div class="ring" style="--p:${pct}%"><span>${pct}%</span></div><div><h2>Master curriculum progress</h2><p>${done} of 112 source pages marked studied. The app keeps all Parts 1–4 available even when pages are unmarked.</p><button class="btn danger" data-reset-progress>Reset local progress</button></div></div></section></div>`}
function openImage(name){const ref=(imageMap.references||[]).find(r=>r.image===name);$('#lightbox').innerHTML=`<div class="modal-box"><button class="close" data-close>×</button><h2>Original source illustration</h2><img src="assets/images/${esc(name)}" alt="Original source illustration"><p class="part-meta">${esc(name)} · Source PDF page ${ref?.page||'—'}</p></div>`;$('#lightbox').classList.remove('hidden')}
function chunkText(text,max=210){const raw=String(text||'').replace(/[🇯🇵🇬🇧🇱🇰]/g,'').replace(/\s+/g,' ').trim();if(!raw)return[];const parts=raw.match(/[^.!?。！？]+[.!?。！？]?/g)||[raw];const out=[];let buf='';for(const part of parts){const next=(buf+' '+part).trim();if(next.length>max&&buf){out.push(buf);buf=part.trim()}else buf=next}if(buf)out.push(buf);return out}
let voiceQueue=[],voiceBusy=false;function pickVoice(lang){const vs=speechSynthesis.getVoices();const base=lang.toLowerCase().split('-')[0];const preferred=vs.find(v=>v.lang.toLowerCase()===lang.toLowerCase()&&/(female|nanami|haruka|sayaka|kyoko|yuki|google|microsoft)/i.test(v.name));return preferred||vs.find(v=>v.lang.toLowerCase()===lang.toLowerCase())||vs.find(v=>v.lang.toLowerCase().startsWith(base))||null}
function speak(text,lang='en-US'){if(!('speechSynthesis'in window)){toast('Speech synthesis is not supported by this browser.');return}const clean=String(text||'').replace(/[🇯🇵🇬🇧🇱🇰]/g,'').replace(/\s+/g,' ').trim();if(!clean)return;speechSynthesis.cancel();voiceQueue=chunkText(clean,150).map(t=>({t,lang}));voiceBusy=true;document.querySelectorAll('.voice.speaking').forEach(x=>x.classList.remove('speaking'));const active=[...document.querySelectorAll('[data-speak]')].find(x=>x.dataset.speak===text&&x.dataset.lang===lang);active?.classList.add('speaking');$('#onlineBadge').textContent=`🔊 ${lang}`;playNext()}
function playNext(){if(!voiceQueue.length){voiceBusy=false;document.querySelectorAll('.voice.speaking').forEach(x=>x.classList.remove('speaking'));$('#onlineBadge').textContent='● Offline-ready';return}const item=voiceQueue.shift(),v=pickVoice(item.lang);if(!v){voiceBusy=false;document.querySelectorAll('.voice.speaking').forEach(x=>x.classList.remove('speaking'));$('#onlineBadge').textContent='● Voice unavailable';toast(`No ${item.lang} voice is installed on this device.`);return}const u=new SpeechSynthesisUtterance(item.t);u.voice=v;u.lang=v.lang;u.rate=.9;u.pitch=1;u.onend=()=>setTimeout(playNext,70);u.onerror=()=>setTimeout(playNext,70);speechSynthesis.speak(u)}
function stopVoice(){voiceQueue=[];voiceBusy=false;speechSynthesis?.cancel();document.querySelectorAll('.voice.speaking').forEach(x=>x.classList.remove('speaking'));$('#onlineBadge').textContent='● Offline-ready'}
document.addEventListener('click',e=>{const n=e.target.closest('[data-view]');if(n){state.view=n.dataset.view;state.lesson=null;render();$('#sidebar').classList.remove('open');return}const g=e.target.closest('[data-go]');if(g){state.view=g.dataset.go;state.lesson=null;render();return}const l=e.target.closest('[data-lesson]');if(l){state.view='study';state.lesson=l.dataset.lesson;render();return}if(e.target.closest('[data-back]')){state.lesson=null;render();return}if(e.target.closest('[data-study-top]')){window.scrollTo({top:0,behavior:'smooth'});return}const m=e.target.closest('[data-mark]');if(m){const p=getProgress();p.read=p.read||{};p.read[m.dataset.mark]=!p.read[m.dataset.mark];saveProgress(p);render();toast(p.read[m.dataset.mark]?'Page marked studied':'Page unmarked');return}const o=e.target.closest('[data-opt]');if(o){if(state.answered)return;state.answered=true;const q=mcqs[state.quizOrder[state.quizIndex%state.quizOrder.length]],idx=+o.dataset.opt,p=getProgress();p.attempts=(p.attempts||0)+1;document.querySelectorAll('.option').forEach((el,i)=>{if(i===q.answer)el.classList.add('correct')});if(idx===q.answer)p.correct=(p.correct||0)+1;else o.classList.add('wrong');saveProgress(p);$('#feedback').innerHTML=`<div class="feedback ${idx===q.answer?'good':'bad'}"><b>${idx===q.answer?'Correct':'Review'}</b><p>${esc(q.why||q.explanation||'Review the related study material.')}</p></div>`;return}if(e.target.closest('[data-next]')){state.quizIndex++;state.answered=false;render();return}if(e.target.closest('[data-reset-quiz]')){state.quizIndex=0;state.answered=false;state.quizOrder=mcqs.map((_,i)=>i);render();return}const jp=e.target.closest('[data-jpset]');if(jp){state.jpSet=jp.dataset.jpset;render();return}const s=e.target.closest('[data-speak]');if(s){speak(s.dataset.speak,s.dataset.lang);return}const im=e.target.closest('[data-image]');if(im){openImage(im.dataset.image);return}if(e.target.closest('[data-close]')){$('#lightbox').classList.add('hidden');return}const os=e.target.closest('[data-open-study]');if(os){const page=+os.dataset.openStudy;const lesson=lessonForPage(page);state.view='study';state.lesson=lesson?.id||'l1';render();setTimeout(()=>document.getElementById(`page-${page}`)?.scrollIntoView({behavior:'smooth'}),120);return}if(e.target.closest('[data-reset-progress]')){localStorage.removeItem(progressKey);render();toast('Progress reset');return}});
document.addEventListener('input',e=>{if(e.target.id==='searchInput'){state.search=e.target.value;search()}if(e.target.id==='visualSearch'){state.visualSearch=e.target.value;visuals()}});
$('#menuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('#stopVoice').addEventListener('click',stopVoice);$('#themeBtn').addEventListener('click',()=>{state.theme=state.theme==='dark'?'light':'dark';applyTheme()});
async function init(){try{const urls=['data/pages.json','data/study.json','data/curriculum.json','data/mcq.json','data/image-map.json','data/japanese-questions.json','data/visual-groups.json','data/japanese-care.json'];const [pr,st,cu,mq,im,jp,vg,jc]=await Promise.all(urls.map(u=>fetch(u).then(r=>{if(!r.ok)throw Error(u);return r.json()})));pages=pr.pages||[];studyPages=st.pages||[];curriculum=cu;mcqs=mq;imageMap=im;jpData=jp;visualGroups=vg;jpCare=jc;state.quizOrder=mcqs.map((_,i)=>i);render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});}catch(e){app.innerHTML=`<div class="main"><div class="empty"><h2>Study data could not load</h2><p>${esc(e.message)}</p></div></div>`;console.error(e)}}
init();